"""
CyberSentry Report Generator.
Produces weekly security reports as rich text + PDF export.
Uses ReportLab for PDF generation.
"""
from __future__ import annotations

import io
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


@dataclass
class ReportData:
    title: str
    project_name: str
    generated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    score: float = 0.0
    grade: str = "F"
    score_delta: float | None = None
    critical_count: int = 0
    high_count: int = 0
    medium_count: int = 0
    low_count: int = 0
    secrets_found: int = 0
    vulnerable_deps: int = 0
    attacks_detected: int = 0
    findings: list[dict[str, Any]] = field(default_factory=list)
    top_recommendations: list[str] = field(default_factory=list)
    scan_coverage: list[str] = field(default_factory=list)


class ReportGenerator:
    """Generate security reports in multiple formats."""

    def generate_text_report(self, data: ReportData) -> str:
        """Generate a plain-text summary report."""
        delta_str = ""
        if data.score_delta is not None:
            arrow = "↑" if data.score_delta >= 0 else "↓"
            delta_str = f" ({arrow}{abs(data.score_delta):.1f} vs last week)"

        lines = [
            "=" * 60,
            f"  CyberSentry Security Report",
            f"  {data.project_name}",
            f"  Generated: {data.generated_at.strftime('%Y-%m-%d %H:%M UTC')}",
            "=" * 60,
            "",
            f"SECURITY SCORE: {data.score:.1f}/100 [{data.grade}]{delta_str}",
            "",
            "FINDINGS SUMMARY",
            f"  Critical : {data.critical_count}",
            f"  High     : {data.high_count}",
            f"  Medium   : {data.medium_count}",
            f"  Low      : {data.low_count}",
            "",
            "ADDITIONAL CHECKS",
            f"  Hardcoded secrets : {data.secrets_found}",
            f"  Vulnerable deps   : {data.vulnerable_deps}",
            f"  Attacks detected  : {data.attacks_detected}",
            "",
        ]

        if data.top_recommendations:
            lines.append("TOP RECOMMENDATIONS")
            for rec in data.top_recommendations[:5]:
                lines.append(f"  • {rec}")
            lines.append("")

        if data.findings:
            lines.append("OPEN FINDINGS")
            for i, f in enumerate(data.findings[:20], 1):
                sev = f.get("severity", "").upper()
                title = f.get("title", "")
                location = f.get("file_path", "")
                lines.append(f"  [{i:2d}] [{sev:8s}] {title}")
                if location:
                    lines.append(f"            {location}")
            if len(data.findings) > 20:
                lines.append(f"  ... and {len(data.findings) - 20} more (see full report)")
            lines.append("")

        lines += ["=" * 60, "  Generated by CyberSentry — developer-first security", "=" * 60]
        return "\n".join(lines)

    def generate_pdf(self, data: ReportData, output_path: Path) -> Path:
        """Generate a PDF security report using ReportLab."""
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.lib import colors
            from reportlab.platypus import (
                SimpleDocTemplate, Paragraph, Spacer, Table,
                TableStyle, HRFlowable,
            )
            from reportlab.lib.enums import TA_CENTER, TA_LEFT
        except ImportError:
            raise ImportError("reportlab is required for PDF export. pip install reportlab")

        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72,
        )

        styles = getSampleStyleSheet()
        story = []

        # Custom styles
        title_style = ParagraphStyle(
            "CSTTitle",
            parent=styles["Title"],
            fontSize=24,
            spaceAfter=6,
            textColor=colors.HexColor("#1a1a2e"),
        )
        h2_style = ParagraphStyle(
            "CSH2",
            parent=styles["Heading2"],
            fontSize=14,
            spaceBefore=12,
            spaceAfter=6,
            textColor=colors.HexColor("#16213e"),
        )
        body_style = styles["Normal"]
        body_style.fontSize = 11

        # Grade color
        grade_colors = {
            "A+": colors.HexColor("#22c55e"),
            "A": colors.HexColor("#22c55e"),
            "A-": colors.HexColor("#86efac"),
            "B+": colors.HexColor("#84cc16"),
            "B": colors.HexColor("#eab308"),
            "B-": colors.HexColor("#f59e0b"),
            "C+": colors.HexColor("#f97316"),
            "C": colors.HexColor("#ef4444"),
            "D": colors.HexColor("#dc2626"),
            "F": colors.HexColor("#7f1d1d"),
        }

        # ── Title ──────────────────────────────────────────────────────────
        story.append(Paragraph("CyberSentry Security Report", title_style))
        story.append(Paragraph(f"<b>{data.project_name}</b>", styles["Heading3"]))
        story.append(Paragraph(
            f"Generated: {data.generated_at.strftime('%B %d, %Y at %H:%M UTC')}",
            styles["Normal"],
        ))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))
        story.append(Spacer(1, 12))

        # ── Score card ─────────────────────────────────────────────────────
        story.append(Paragraph("Security Score", h2_style))
        g_color = grade_colors.get(data.grade, colors.gray)

        delta_text = ""
        if data.score_delta is not None:
            arrow = "↑" if data.score_delta >= 0 else "↓"
            delta_text = f" ({arrow}{abs(data.score_delta):.1f} vs previous scan)"

        score_data = [
            ["Score", "Grade", "Critical", "High", "Medium", "Low"],
            [
                f"{data.score:.1f}/100{delta_text}",
                data.grade,
                str(data.critical_count),
                str(data.high_count),
                str(data.medium_count),
                str(data.low_count),
            ],
        ]
        score_table = Table(score_data, colWidths=[1.8 * inch, 0.8 * inch, 0.8 * inch, 0.8 * inch, 0.8 * inch, 0.8 * inch])
        score_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 10),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTNAME", (0, 1), (0, 1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 1), (0, 1), 14),
            ("TEXTCOLOR", (1, 1), (1, 1), g_color),
            ("FONTNAME", (1, 1), (1, 1), "Helvetica-Bold"),
            ("FONTSIZE", (1, 1), (1, 1), 18),
            ("TEXTCOLOR", (2, 1), (2, 1), colors.HexColor("#dc2626")),
            ("TEXTCOLOR", (3, 1), (3, 1), colors.HexColor("#ea580c")),
            ("TEXTCOLOR", (4, 1), (4, 1), colors.HexColor("#ca8a04")),
            ("TEXTCOLOR", (5, 1), (5, 1), colors.HexColor("#2563eb")),
            ("FONTNAME", (2, 1), (-1, 1), "Helvetica-Bold"),
            ("FONTSIZE", (2, 1), (-1, 1), 14),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#f8fafc"), colors.white]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("PADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(score_table)
        story.append(Spacer(1, 16))

        # ── Recommendations ────────────────────────────────────────────────
        if data.top_recommendations:
            story.append(Paragraph("Top Recommendations", h2_style))
            for rec in data.top_recommendations[:5]:
                story.append(Paragraph(f"• {rec}", body_style))
                story.append(Spacer(1, 4))
            story.append(Spacer(1, 12))

        # ── Findings table ─────────────────────────────────────────────────
        if data.findings:
            story.append(Paragraph(f"Open Findings ({len(data.findings)} total)", h2_style))

            _sev_colors = {
                "critical": colors.HexColor("#dc2626"),
                "high": colors.HexColor("#ea580c"),
                "medium": colors.HexColor("#ca8a04"),
                "low": colors.HexColor("#2563eb"),
            }

            finding_rows = [["#", "Severity", "Type", "Title", "Location"]]
            for i, f in enumerate(data.findings[:30], 1):
                finding_rows.append([
                    str(i),
                    f.get("severity", "").upper(),
                    f.get("finding_type", ""),
                    (f.get("title", ""))[:50],
                    (f.get("file_path", "") or "")[:30],
                ])

            f_table = Table(
                finding_rows,
                colWidths=[0.4 * inch, 0.7 * inch, 1.0 * inch, 2.5 * inch, 1.8 * inch],
            )

            # Build per-row severity coloring
            table_style = [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("ALIGN", (0, 0), (1, -1), "CENTER"),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
                ("PADDING", (0, 0), (-1, -1), 5),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#f8fafc"), colors.white]),
            ]
            for row_idx, finding in enumerate(data.findings[:30], 1):
                sev = finding.get("severity", "low").lower()
                sc = _sev_colors.get(sev, colors.gray)
                table_style.append(("TEXTCOLOR", (1, row_idx), (1, row_idx), sc))
                table_style.append(("FONTNAME", (1, row_idx), (1, row_idx), "Helvetica-Bold"))

            f_table.setStyle(TableStyle(table_style))
            story.append(f_table)

        # ── Footer ─────────────────────────────────────────────────────────
        story.append(Spacer(1, 24))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0")))
        story.append(Spacer(1, 6))
        story.append(Paragraph(
            "Generated by CyberSentry — developer-first security | Attack → Detect → Explain → Fix",
            ParagraphStyle("footer", parent=styles["Normal"], fontSize=8, textColor=colors.gray, alignment=TA_CENTER),
        ))

        doc.build(story)
        return output_path

    def save_text_report(self, data: ReportData, output_path: Path) -> Path:
        """Save plain text report to file."""
        text = self.generate_text_report(data)
        output_path.write_text(text, encoding="utf-8")
        return output_path
